### ISSUE TITLE
작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by Alpha-Dvlp** [STR-HK/hdl-stubs#1]
2022 04 09일 기준으로 작동이 안되는 것 같습니다. 제가 사용법을 모르거나요... 혹시 readme로 사용법 알려주실수 있으신가요?
블랙툰이 url형식이 다른 곳들과는 좀 다르더군요. 평범한 8반을 예로 들면 https://blacktoon165.com/webtoon/815.html 이런식 입니다.

**Comment by STR-HK** [comment]
히토미 다운로더 레포지토리에서 해결
